### ISSUE TITLE
anti-affinity by default for better availability.

### ISSUE THREAD

**Issue by sjhx** [IBM/portieris#115]
To guard against node loss causing loss of service and cluster deadlock we should configure anti-affinity by default probably here:
https://github.com/IBM/portieris/blob/master/helm/portieris/values.yaml

**Comment by rubroboletus** [comment]
Good idea, just think, if use requiredDuringSchedulingIgnoredDuringExecution or preferredDuringSchedulingIgnoredDuringExecution. Most K8s clusters have more than one worker node and requiring this during scheduling is, I think, much better.
Also, for better scheduling the portieris pods, declaring resource limits and requests by default should be better.

**Comment by sjhx** [comment]
The thinking behind 'preferred' is that on a cluster where only a single node is elligible for some reason we still want more than a single instance of portieris.  Raised: https://github.com/IBM/portieris/issues/120 for resources, Thanks.

**Comment by sjhx** [comment]
done
