### ISSUE TITLE
Use v1 api for CRD

### ISSUE THREAD

**Issue by molepigeon** [IBM/portieris#121]
CustomResourceDefinition has been promoted to V1 in 1.16. It adds some new features that are handy, like support for openapi spec in the definition. The beta1 spec might be lined up for deletion at some point too.

**Comment by sjhx** [comment]
In addition to the deprecation / lack of validation / there is also the issue that the CRD name was inherited from an IBM internal deliverable so has an incompatible CRD of the same name leading to issue. Propose to switch name at the same time as introducing v1, expect this will be a breaking change.
