### ISSUE TITLE
permission denied on Openshift

### ISSUE THREAD

**Issue by jeffhoek** [IBM/portieris#124]
# What commit ID of Portieris did you experience the problem with?
helm3 branch (79f8c77 on Apr 20), with master merged in (136fab7)

### What went wrong?
Helm installed Portieris but the pods are in CrashLoopBackoff with log:
```
log: exiting because of error: log: cannot create log: open /tmp/trust.portieris-6d9566657c-27cmd.unknownuser.log.INFO.20200610-195916.1: permission denied
```

### What should have happened differently?
Portieris deployment pods should not CrashLoopBackoff.

### How can it be reproduced?
```
oc login ...
git clone --single-branch --branch helm3 https://github.com/IBM/portieris.git
cd portieris
helm upgrade --install portieris --set namespace=portieris helm/portieris
Release "portieris" does not exist. Installing it now.
NAME: portieris
LAST DEPLOYED: Wed Jun 10 15:58:19 2020
NAMESPACE: portieris
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Portieris is installed in your cluster.
...
oc logs deployment.apps/portieris
...
log: exiting because of error: log: cannot create log: open /tmp/trust.portieris-6d9566657c-27cmd.unknownuser.log.INFO.20200610-195916.1: permission denied
```

### Any other relevant information
In order to fix, we can add a security context constraint (scc) for the portieris service account, and explicitly specify the `runAsUser.MustRunAs` UID value.

I have tested this fix on IBM managed OpenShift 4.3 and will submit a pull request.

**Comment by sjhx** [comment]
I think that value is set in the latest master branch, something lost in merge?
