### ISSUE TITLE
can't  visit  link in Readme It is like a black page

### ISSUE THREAD

**Issue by yuzp1996** [IBM/portieris#158]
### What went wrong?
I can not visit the link in page ReadMe.md https://cloud.ibm.com/docs/Registry?topic=Registry-security_enforce#assign_user_policy  It like it is a blank page

**Comment by yuzp1996** [comment]
Is it a bad link?

**Comment by molepigeon** [comment]
Hi, that link works for me, it goes to a section called "Controlling who can customize policies" in the IBM Cloud docs.

Try clearing your cache and cookies or try a different browser.

If you can access the IBM Cloud docs through Google search results, you can search for  "ibm cloud docs container image security enforcement" and the first result (for me) is a topic called "Enforcing container image security - IBM Cloud" which contains the section that the link points to.

**Comment by yuzp1996** [comment]
> Hi, that link works for me, it goes to a section called "Controlling who can customize policies" in the IBM Cloud docs.
> 
> Try clearing your cache and cookies or try a different browser.
> 
> If you can access the IBM Cloud docs through Google search results, you can search for "ibm cloud docs container image security enforcement" and the first result (for me) is a topic called "Enforcing container image security - IBM Cloud" which contains the section that the link points to.

Thank you very much It help me a lot
