### ISSUE TITLE
Move certs to a more sensible place than hard coding them

### ISSUE THREAD

**Issue by liamawhite** [IBM/portieris#16]
We should wait until the Mutating Admission Webhook spec settles and then they should be moved to Kube secrets.

We should document regenerating certificates for production use as well.

**Comment by zparnold** [comment]
You beat me to it! I was writing up the issue just now. 😄 Since we know that this is going to be running in Kube as a CRD, could we use a volume mount of an SSH secret (just and RSA pub/priv pair) as defined here? https://kubernetes.io/docs/concepts/configuration/secret/#use-case-pod-with-ssh-keys

**Comment by liamawhite** [comment]
I need to do some more reading into exactly which certs/keys are used for what but that all sounds sensible.

**Comment by liamawhite** [comment]
yes, closing.
