### ISSUE TITLE
Portieris certificate error x509: certificate relies on legacy Common Name field

### ISSUE THREAD

**Issue by christiangonre** [IBM/portieris#196]
### What commit ID of Portieris did you experience the problem with?
716c69cd189d37d71a28802a82b2d95898be7d06

### What went wrong?
Once you install successfully portieris in a Kubernetes 1.19.0 over Red Hat 7.8, if you try to pull and image if fails with the following error:

Error from server (InternalError): error when creating "test.yaml": Internal error occurred: failed calling webhook "trust.hooks.securityenforcement.admission.cloud.ibm.com": Post "https://portieris.portieris.svc:443/admit?timeout=30s": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
### What should have happened differently?
It must give a different error because I don´t allow that registry in the policy rules, not a cert error.
### How can it be reproduced?
I installed using the following steps:
1. Clone the git repo.
2. Checkout to version 0.8.2
3. Generate certs using ./helm/portieris/gencerts
4. Remove namespace template file to avoid the "namespace is present problem"
5. Create a namespace with name portieris
6. Apply the helm chart with the following command:
```
helm install portieris --namespace portieris --set IBMContainerService=false helm/portieris
```
7. Once installed Portieris, I must change the MutatingWebhookConfiguration in failurePolicy to Ignore to allow to download the containers in the first installation.  Once the containers restarted, I changed to Fail.
I saw this recommendation in the following link: https://github.com/IBM/portieris/issues/97

### Any other relevant information

Please if you need more info to solve the problem I can help.

Thanks in advance for all, I think this is a very good project!

**Comment by sjhx** [comment]
Thanks for the nice comments, I think we are addressing the problem in 7. (as a by the way in currrent work). 
However I think that the certificate error is new maybe in Kube 1.19, will try to recreate.

**Comment by sjhx** [comment]
this is because kubernetes 1.19 is compiles with golang 1.15 and https://golang.org/doc/go1.15#commonname
