### ISSUE TITLE
New logging from 208 does not contain image details when using simple signing

### ISSUE THREAD

**Issue by jhart1685** [IBM/portieris#216]
### What commit ID of Portieris did you experience the problem with?
0.9.1

### What went wrong?
Testing with signed and unsigned images, the new log entries added in #208 do not contain the `[image:digest]` details that the code suggest should be there.

### What should have happened differently?
In both Allow and Deny cases, details of the allowed/denied images should be present in the logs.

### How can it be reproduced?
Create a policy to enforce simple signing on your images. Attempt to deploy an unsigned image, and inspect the logs.

### Any other relevant information
Logs attached below from a "Deny" case.. But the same problem exists for "Allow".

```text
I1124 16:41:17.402608       1 controller.go:64] Processing admission request for CREATE on test
I1124 16:41:17.523120       1 controller.go:157] Getting policy for container image: uk.icr.io/jhart/volports:example   namespace: default
I1124 16:41:17.636441       1 controller.go:224] ImagePullSecret default/all-icr-io found
I1124 16:41:17.636604       1 enforcer.go:68] policy.Simple {[{signedBy signer {  }}]  }
I1124 16:41:17.674567       1 secret.go:51] Found secret signer
I1124 16:41:17.674658       1 sigStoreConfig.go:37] No lookaside signature store.
I1124 16:41:20.144895       1 imagePolicy.go:69] SimpleSigning verification: ImagePullSecret with username iamapikey for image uk.icr.io/jhart/volports:example was valid (secret 1/1), continuing to next stage
I1124 16:41:20.993800       1 responder.go:93] simple: policy denied the request: A signature was required, but no signature exists
I1124 16:41:20.993835       1 controller.go:118] Deny for images (image:digest)
```

**Comment by jhart1685** [comment]
@guysports FYI

**Comment by guysports** [comment]
@jhart1685 I think there are two problems here

1. The var denials on https://github.com/IBM/portieris/blob/9973a31d52a4552d8d3b9cc7c44ca43df55b26f4/pkg/controller/multi/controller.go#L101 is scoped locally to the for loop, so the logging of denials on https://github.com/IBM/portieris/blob/9973a31d52a4552d8d3b9cc7c44ca43df55b26f4/pkg/controller/multi/controller.go#L86 is just logging an empty map, hence we get the output we do.

2. The local var denials is overwritten on each call to getPatchesForContainers, so for multiple containers the initial messages would be lost.

I'll put together a fix in a PR

**Comment by sjhx** [comment]
assume resolved
