### ISSUE TITLE
Portieris limited support of Openshift deploymentconfigs

### ISSUE THREAD

**Issue by lucaspalm** [IBM/portieris#227]
### What commit ID of Portieris did you experience the problem with?
https://github.com/IBM/portieris/releases/tag/0.9.2

### What went wrong?
With Portieris installed in a ROKS 4.6 cluster, we noticed that when trying to create a pod via a deploymentconfig, Portieris denied the admission request:
```
Deny " ", invalid image name
```

In our case, we were testing using this [deploymentconfig](https://github.com/sclorg/nodejs-ex/blob/master/helm/nodejs/templates/deploymentconfig.yaml#L32), but this issue is applicable to all deploymentconfigs.

### What should have happened differently?
The admission request should have been allowed and the resulting pod should be created and running.

### How can it be reproduced?
1. Create an openshift/ROKS 4.6 cluster.

2. Ensure you are at OC CLI version 4.5/4.6+.
```
oc version --client

Client Version: 4.6.6
```

3. Run the following on an openshift/ROKS 4.6 cluster:
```
oc new-project nodejs-123
oc new-app --name nodejs-123 https://github.com/openshift/nodejs-ex.git -n nodejs-123
```

You should see the pod admission request fail and the pod not start.

The error you will see from the CLI command will be similar to:
```
--> Creating resources ...
    error: admission webhook "trust.hooks.securityenforcement.admission.cloud.ibm.com" denied the request: 
Deny " ", invalid image name
```

### Any other relevant information
The OC CLI version is important here.  The error only seems to happen when using OC CLI version 4.5/4.6+.  When using earlier versions of the CLI, everything works fine.

**Comment by wmlynch** [comment]
Run `oc new-app` with `-v=10` and you can see what really happening.

Starting with oc version 4.5, the new-app is creating a deployment with a `placeholder`  image: " " value.  Then once the image build is complete Openshift will update the deployment with the actual image value.  It is purposely creating a json conformant deployment with an empty image with the intent to update it later.

**Comment by sjhx** [comment]
Since the webhook registers for updates of deployments, it should be safe to alow deployments with blank images, when updated later to a valid image, portieris should be invoked again.
