### ISSUE TITLE
Signing enforcement Denies on RemapIdentity images with worker node docker/config.json aliases

### ISSUE THREAD

**Issue by wmlynch** [IBM/portieris#254]
### What commit ID of Portieris did you experience the problem with?
`portieris:v0.10.0`
### What went wrong?

There seems to be a disconnect with portieris and its processing and the established registry aliasing that has been
setup on a worker node.  Maybe if portieris used the remapped image for inspection, it would be able to proceed.

```
kubectl -n openshift-marketplace rollout restart deploy/marketplace-operator
error: failed to patch: admission webhook "trust.hooks.securityenforcement.admission.cloud.ibm.com" denied the request: 
simple: Deny "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3c01dff6a6e9dd83ed1d15828b4809623672ad4ed647d9df19fceedaaaf720aa", no valid ImagePullSecret, 0 tried
```
Image Policy
```
  - name: quay.io/openshift-release-dev/ocp-v4.0-art-dev*
    policy:
      simple:
        requirements:
        - keySecret: ibm-signed-image-pubkey
          signedIdentity:
            prefix: quay.io/openshift-release-dev/ocp-v4.0-art-dev
            signedPrefix: us.icr.io/armada-master/ocp-release
            type: remapIdentity
          type: signedBy
```
Worker node registry configuration
```
[[registry]]
  location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"
  insecure = false
  blocked = false
  mirror-by-digest-only = true
  prefix = ""

  [[registry.mirror]]
    location = "registry.ng.bluemix.net/armada-master/ocp-release"
    insecure = false
```
Portieris log snippet:
```
I0204 15:13:12.887012       1 controller.go:176] Getting policy for container image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3c01dff6a6e9dd83ed1d15828b4809623672ad4ed647d9df19fceedaaaf720aa   namespace: openshift-marketplace 
E0204 15:13:12.913223       1 controller.go:247] Secret marketplace-operator-dockercfg-zhx8f not defined for registry: quay.io 
I0204 15:13:12.913324       1 enforcer.go:68] policy.Simple {[{signedBy ibm-signed-image-pubkey {remapIdentity   quay.io/openshift-release-dev/ocp-v4.0-art-dev us.icr.io/armada-master/ocp-release}}]  } 
I0204 15:13:12.922997       1 secret.go:51] Found secret ibm-signed-image-pubkey 
I0204 15:13:12.923274       1 sigStoreConfig.go:37] No lookaside signature store. 
E0204 15:13:13.367355       1 imagePolicy.go:58] SimpleSigning verification: anonymous access denied for image quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3c01dff6a6e9dd83ed1d15828b4809623672ad4ed647d9df19fceedaaaf720aa, continuing with ImagePullSecrets... Error Error reading manifest sha256:3c01dff6a6e9dd83ed1d15828b4809623672ad4ed647d9df19fceedaaaf720aa in quay.io/openshift-release-dev/ocp-v4.0-art-dev: unauthorized: access to the requested resource is not authorized 
E0204 15:13:13.367666       1 responder.go:87] simple: Deny "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3c01dff6a6e9dd83ed1d15828b4809623672ad4ed647d9df19fceedaaaf720aa", no valid ImagePullSecret, 0 tried 
```

**Comment by sjhx** [comment]
As a first pass I think this is a not what "remapIdentity" is designed to do.

"remapIdentity" is for the case where the signature was created on and references registry ORIG in its identity and the image is has been moved to registry MIRROR and the deployment is from MIRROR which has a copy original signature/identity from ORIG

in this case the signature is created on and references MIRROR yet the deployment is aparently from ORIG (though manipulated out of sight of kube/portieris to physically come from MIRROR). Portieris therefore attempts to get the manifest and signature from ORIG and fails/denies.

We need to consider how to support such a case in portieris.

**Comment by sjhx** [comment]
The main issue is supporting customers who use worker node configured registry miroring such as that supported on cri-o with https://github.com/containers/image underpinning. 

One options would be to expose the Portieris container to the hosts registry configuration, or a copy of it, however this seems to have some downsides, there is already some registry configuration going on inside the container to support the signature storage options and we would have to be careful not to conflict, such configurations would only be picked up by the "simple" support since its the same library and not by "vulnerability" or "trust" policies, and what if the hosts are not all configured identically?

Probably a better option is to  have a policy based mapping which needs to be set such that portieris is aware of the physical location of the image, which can apply to all policies.

**Comment by sjhx** [comment]
Having thought about this some more, I think that the scope of Portieris is to provide a Kube native signature policy independent of the Kubernetes platform/runtime. There are certainly pros and cons to this and different pros and cons to using the node/host based runtime configuration, but to do both and have them coexist and cooperate, maximises complexity and minimises consumability so I propose to close this as out of scope / will not do. 
Suggestion would be to either use Portieris OR host based configuration image config.
If there other drivers to use the host based onfiguration of the containers/image library and a need to conveniently support simple signatures then perhaps a different solution to the problem would be to create a Kube native configuration mechanism for it (think daemon-set writing config files driven by similar policies and public key resources - no namespaced resources).
