### ISSUE TITLE
Daemonset admission not handled appropriately

### ISSUE THREAD

**Issue by lumjjb** [IBM/portieris#27]
### What went wrong?

The admission webhook rejected daemonset admissions

### What should have happened differently?

It should admit the daemonset based on the policy in place

### How can it be reproduced?
```
kubectl -n kube-system edit daemonset calico-node
# make some changes.
error: daemonsets "calico-node" could not be patched: Internal error occurred: admission webhook "trust.hooks.securityenforcement.admission.cloud.ibm.com" denied the request:
The resource "extensions/v1beta1/daemonsets" is not supported. Make sure that you are using a supported kubectl version, and that you are using a supported Kubernetes workload type
```

**Comment by molepigeon** [comment]
Hi, thanks for the report! I'd be happy to look into this.

It looks like extensions/v1beta1/daemonsets should be supported - it was added in a commit at the start of May: https://github.com/IBM/portieris/commit/17764c74186a2d69611b216d590c67f7286cb0f6#diff-0723a5c0bbf7cfd8e11c95b5195b35ecR160

Please could you confirm that you're running from a commit that's later than the one I've linked?

**Comment by lumjjb** [comment]
Hi @molepigeon. Thanks. I am on master with commit 51fde44aa35597d45afb86cc183fb17b7b05e915 on Jun 29. So it should 

My installation process was with `helm install -n portieris helm/portieris`.

Looks like the commit exists too:
```
➜  portieris git:(master) git log | grep 17764c74186a2d69611b216d590c67f7286cb0f6 -A 5
commit 17764c74186a2d69611b216d590c67f7286cb0f6
Author: Jack Baines <jack.baines@uk.ibm.com>
Date:   Tue May 1 15:43:11 2018 +0100

    Add support for the supported resources at all current API versions
```

**Comment by lumjjb** [comment]
Was the problem reproducible on  your end?

**Comment by molepigeon** [comment]
Yes, sorry for the delay in responding @lumjjb - looks like we published an updated image to Docker Hub when we added support for other resource types like DaemonSets, but forgot to update the chart to point to it.

There's a PR above to get that fixed in master, but if you want to test the change for yourself, you can edit `helm/portieris/values.yaml` and change the `tag` from `0.2.0` to `0.3.0`.
