### ISSUE TITLE
Unhandled errors in simple verifier.

### ISSUE THREAD

**Issue by brackendawson** [IBM/portieris#273]
### What commit ID of Portieris did you experience the problem with?
v0.10.0

### What went wrong?
No actual error. Code inspection reveals missing error handling.

### Any other relevant information
- [ ] Error from this likely call to the registry is not checked: https://github.com/IBM/portieris/blob/c829db9add3096cc50c4c664927b61bd3bca8996/pkg/verifier/simple/imagePolicy.go#L93
- [ ] Error treated blindly treated as deny: https://github.com/IBM/portieris/blob/master/pkg/verifier/simple/imagePolicy.go#L87-L90 The error type should be checked and handled like so:
```go
switch err.(type) {
case nil:
case signature.PolicyRequirementError:
	return nil, err, nil
default:
	return nil, nil, err
}
```

**Comment by sjhx** [comment]
addressed
