### ISSUE TITLE
Invalid struct tag

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [IBM/portieris#276]
https://github.com/IBM/portieris/blob/122a04f704e0fd5599988ce097b427b194ead2fd/pkg/apis/portieris.cloud.ibm.com/v1/types.go#L115

`omitEmpty` and `inline` are invalid tags. Pay attention to capitalization.

**Comment by sjhx** [comment]
Thanks for the report. I understand the typo in omitEmpty, however I believe inline is valid. https://github.com/vmihailenco/msgpack/pull/40/files

**Comment by adrianos93** [comment]
@sjhx seems as though the `inline` struct tag does not actually exist. It is still a proposal for it to be added to `encoding/json`. Created a PR to remove them.
