### ISSUE TITLE
Wrong usage of break statement

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [IBM/portieris#277]
https://github.com/IBM/portieris/blob/122a04f704e0fd5599988ce097b427b194ead2fd/pkg/verifier/vulnerability/ibm_va.go#L116

https://github.com/IBM/portieris/blob/122a04f704e0fd5599988ce097b427b194ead2fd/pkg/verifier/vulnerability/ibm_va.go#L156

The break statement means "break" case block instead of loop block. 
You should add a label to the break statement if you want to break for loop.

**Comment by sjhx** [comment]
I don't believe either case is trying to break the for loop. Thanks for the attention though.
