### ISSUE TITLE
Add ability to set additional deployment `podAnnotations` in Helm Chart

### ISSUE THREAD

**Issue by dylanhitt** [IBM/portieris#323]
**Is your feature request related to a problem? Describe the feature request.**
There currently isn't support for setting `podAnnotations`. Not being able to set podAnnotations creates funky workarounds when you have the requirement to apply annotations do to some compliance standard.

**Describe the solution that you'd like**
Ability to pass `podAnnotations: {}` in `values.yaml`

**Describe alternatives you've considered**
Current workaround is `kubectl patch`

I intend to submit a Pull Request for this issue.

**Comment by sjhx** [comment]
Thanks for this contribution - appreciated.
