### ISSUE TITLE
Update k8s.io libraries to solve vulnerabilities

### ISSUE THREAD

**Issue by adrianos93** [IBM/portieris#368]
**Is your feature request related to a problem? Describe the feature request.**
Currently used versions of k8s.io/client-go, k8s.io/apimachinery and k8s.io/api is vulnerable.

**Describe the solution that you'd like**
Update the versions which should resolve the vulnerability

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sjhx** [comment]
Optimistically closing this on the basis that libs have been updated and that we have dependency vulnerability check in the build process (nancy). If you believe there is still a problem please re-open and indicate your finding and how to get them. Thanks for raising.
