### ISSUE TITLE
Openshift verify image signing

### ISSUE THREAD

**Issue by chengjun0124** [IBM/portieris#371]
Hi team

Our team is using jfrog artifactory(https://na.artifactory.swg-devops.com/) storing container image. We have signed our images by Sode Signing Service(https://pgawdccosig01.sl.bluecloud.ibm.com/), and stored the signature in a repository in jfrog artifactory. 

https://access.redhat.com/articles/3116561 says openshift can verify image signing for Red Hat Container Registry. We'd like to use similar way to verify our images, but the question is our images and signature are in jfrog artifactory. In this case, is it possible to verify image signing like https://access.redhat.com/articles/3116561? Thanks.

I am sorry if here is not the right place where I should post my question.

Best Regards
Jun
juncheng@cn.ibm.com

**Comment by sjhx** [comment]
Yes it is possible to have Portieris verify signatures on images deployed from JFrog artifactory.
You must have the image in a JFrog docker repository and the signature in a JFrog generic respository.
You should use the `storeURL`  and `storeSecret` properties to access the signature in the generic repo.
There is an example of such a policy in [this section.](https://github.com/IBM/portieris/blob/main/POLICIES.md#simple-red-hat-simple-signing)
Feel free to reopen the issue if there are further questions.
