### ISSUE TITLE
Revisit jobs in helm chart

### ISSUE THREAD

**Issue by molepigeon** [IBM/portieris#41]
When we first launched, Helm didn't support a number of things that we needed, like creating custom resource definitions. So we created a number of Jobs in the chart that spun up a kubectl pod to apply yamls against the cluster.

I believe that the things we need are now supported, and so we can revisit the chart and try to create them in-line rather than spin up a kubectl pod. This would improve the experience when the chart fails to install, since there won't be jobs lying around that prevent you from re-running the chart installation.

**Comment by laeven** [comment]
Hello, I submitted a PR (#50) In hopes to help out, I would appreciate any feedback.
There were some limitations detailed in the helm Github when trying to deal with this such as "Resources generated by helm hooks are not handled during resource clean up" which required the use of jobs for creation. There's also limitations when performing upgrades which I am currently investigating, but I wanted some opinions and help on those parts.

**Comment by molepigeon** [comment]
Fixed by https://github.com/IBM/portieris/pull/176
