### ISSUE TITLE
Chart does not create ibm-system namespace

### ISSUE THREAD

**Issue by molepigeon** [IBM/portieris#42]
All the Portieris components install into the ibm-system Kubernetes namespace. But the chart doesn't create the namespace before trying to install into it. That's not a problem on IKS, since the ibm-system namespace exists out of the box, but will cause the chart to fail to install on other platforms until the ibm-system namespace is created manually.

To fix this, we can add a yaml into the chart to create the namespace. We should annotate it with `"helm.sh/hook": "pre-install"` so that the namespace is created before any of the resources.

**Comment by jjonly** [comment]
You forgot to use the helm variable for the namespace in 
`portieris/helm/portieris/templates/secret.yaml`
There it is still hardcoded.

**Comment by molepigeon** [comment]
@jjonly Oops! Well spotted, I've raised https://github.com/IBM/portieris/pull/47 to correct that.

**Comment by ams0** [comment]
Opened #68 to also change the generated cert names to include the namespace.

**Comment by sjhx** [comment]
helm 3.2.0 will have the option to create namespaces there is nothing to do in portieris https://github.com/helm/helm/issues/4456#issuecomment-607927999
