### ISSUE TITLE
Portieris container not signed with DCT 

### ISSUE THREAD

**Issue by zparnold** [IBM/portieris#65]
### What commit ID of Portieris did you experience the problem with?
Master (0.5.2)
### What went wrong?
I tried to pull the Docker Content Trust image locally on my machine and there is no valid trust data for it

```
Error: remote trust data does not exist for docker.io/ibmcom/portieris: notary.docker.io does not have trust data for docker.io/ibmcom/portieris
```
### What should have happened differently?
It should have valid trust data
### How can it be reproduced?
`docker pull docker.io/ibmcom/portieris:0.5.2`

**Comment by jerrinss5** [comment]
@zparnold make sure that whitelist portieris to run in the cluster with the following policy.
`# Policies off the bat
---
apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: ImagePolicy
metadata:
  name: portieris-default-image-policy
  namespace: kube-system
spec:
   repositories:
    # This policy prevents Portieris from blocking itself
    - name: "docker.io/ibmcom/portieris:0.5.2"
      policy:`

**Comment by zparnold** [comment]
Ok thanks. Shouldn't the thing that's enforcing DCT also be signed via DCT though?

**Comment by jerrinss5** [comment]
It's a catch 22 problem. Although it can be signed, the code to verify resides within the image. So basically to verify we need that portieris image to run as whitelisted.
The admission control tries to find the code and if doesn't find it fails closed.

**Comment by sjhx** [comment]
Although not signed with DCT, which we expect will be deprecated n favour of Notary 2, it is now signed with a RedHat style simple signature. Would completion of #205  satisfy this issue?

**Comment by sjhx** [comment]
Feel free to re-open if you feel DCT is still needed.
