### ISSUE TITLE
Missing Prometheus metrics

### ISSUE THREAD

**Issue by tomhau01** [IBM/portieris#67]
### What commit ID of Portieris did you experience the problem with?
939c65b4e121c778d97f5dd1384484f5fcb078f1 - 0.5.2

### What went wrong?
Portieris doesnt support (Prometheus) metrics collection - a vital part of making the project production ready. Having metrics to alert on error situations is critical, and metrics for example for denied images would be very handy.

### What should have happened differently?
Please consider providing metrics from the project.

**Comment by sjhx** [comment]
Thanks for the issue, basic metrics were added in #208
