### ISSUE TITLE
Set priorityClassName 

### ISSUE THREAD

**Issue by sjhx** [IBM/portieris#78]
Kubernetes v1.11 supports https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/ which allows pods to be considered critical to the cluster. Portieris pods should consider setting priorityClassName in the pod spec to system-node-critical, system-cluster-critical or a priority class unique to Portieris pods. This is a Kubernetes v1.11 only feature and cannot be set in previous releases.

**Comment by bainsy88** [comment]
Having looked at this I think out of the 2 built in priorities `system-cluster-critical` would make sense. Looking at a cluster the top level `system-node-critical` ones these are things like the CNI such as Calico which Portieiris will need to be up in order for things to work, so coming one level below that seems sensible.

**Comment by sjhx** [comment]
implemented
