### ISSUE TITLE
Examples in README.md don't work with latest helm (v2 or v3)

### ISSUE THREAD

**Issue by jherwitz** [IBM/portieris#87]
The examples in the top-level README don't work for the latest version of `helm` (currently 3.1.1 via `brew`). 

### What commit ID of Portieris did you experience the problem with?
`ec999a46ec207a11d685e036ade20a79dcdc8a37`

### What went wrong?
Example commands that don't work:

```bash
$ helm upgrade --install --name portieris -n portieris --set namespace=default helm/portieris
Error: unknown flag: --name
```

```bash
$ helm delete --purge portieris
Error: unknown flag: --purge
```

### What should have happened differently?
README should list maximum compatible version of helm, or the commands should be updated for the latest version.

### How can it be reproduced?
`brew install helm` and run through the README.

**Comment by jherwitz** [comment]
This appears to not work for `2.16` as well:

```
$ helm version
Client: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
$ helm upgrade --install --name portieris -n portieris --set namespace=default helm/portieris
Error: unknown flag: --name
```

**Comment by patmantru** [comment]
Me too...  This made following the instructions difficult and frustrating.
