### ISSUE TITLE
Test and support Helm 3

### ISSUE THREAD

**Issue by molepigeon** [IBM/portieris#89]
In theory, every chart that's built for Helm 2 should be forward compatible with Helm 3. However, there's some uncertainty about whether the install hooks for installing the policy CRDs will work correctly in Helm 3. We need to know that the chart install works before we can say with confidence that we support Helm 3.

Plus, Helm 3 doesn't have the `--purge` option on `helm delete`, so we'd need to document around that.

**Comment by sjhx** [comment]
@molepigeon can we close this now?

**Comment by sjhx** [comment]
Well I think we can :)
