### ISSUE TITLE
Mutated image reference has both tag and digest.

### ISSUE THREAD

**Issue by sjhx** [IBM/portieris#90]
I would expect a tag to be replaced by the digest.
Is this form of image reference formally supported or is it working by luck?
Does the tag add any value? Does the image still need to have the tag?

Unless we somehow depend on this I poropose removing the tag from the mutated image reference.

**Comment by mtrmac** [comment]
The tag is completely ignored by recent implementations, so depending on point of view it can be either documentation or possibly misleading.

_After_ https://github.com/cri-o/cri-o/pull/3060 it should work fine; before CRI-O would reject it.
