### ISSUE TITLE
oauth helper ignores user-specified custom ca certificates

### ISSUE THREAD

**Issue by josephdrichard** [IBM/portieris#99]
### What commit ID of Portieris did you experience the problem with?
https://github.com/IBM/portieris/commit/b62ded2a4d9a73818fdda2b9e76e4b8f621107aa

### What went wrong?
Unable to get content trust token from notary server with certificate signed by specified custom certificate authority

### What should have happened differently?
Request should have worked with server certificate signed by specified custom ca certificates.

### How can it be reproduced?
Deploy with a notary server that uses a certificate signed by a non-default certificate, with the ca cert passed in to /etc/certs/ca.pem.

### Any other relevant information
https://github.com/IBM/portieris/blob/master/helpers/oauth/oauth.go does not use specified custom ca certs, as is done from https://github.com/IBM/portieris/blob/master/pkg/notary/notary.go#L45

**Comment by josephdrichard** [comment]
Can someone assign this issue to me?  I am starting working on a fix.

**Comment by molepigeon** [comment]
Closed by #99
